name: shelf_example_flutter
description: A new Flutter project.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.5
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  path_provider: ^2.0.11
  objectbox: ^1.6.2
  objectbox_flutter_libs: ^1.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  objectbox_generator: ^1.6.2
  flutter_lints: ^2.0.0
  build_runner: ^2.3.2 


flutter:

  uses-material-design: true

